---
# tasks file for dynatrace.activegate
- name: Check required Variables
  fail:
    msg: "One or more required Variables are not defined"
  when: not dynatrace_activegate_role_task or not dynatrace_environment_url or not dynatrace_paas_token

- name: load default variables based on os
  include_vars: "defaults/{{ansible_system | lower}}.yml"

- name: load variables based on os
  include_vars: "vars/{{ansible_system | lower}}.yml"

- name: download dynatrace activegate
  include_tasks: "tasks/download.yml"
  when: dynatrace_activegate_role_task == 'install' or dynatrace_activegate_role_task == 'update'

- name: load task based on role task
  include_tasks: "tasks/{{dynatrace_activegate_role_task}}.yml"
